#############################################################################
# Makefile for building: Rationality
# Generated by qmake (2.01a) (Qt 4.6.3) on: mer giu 30 17:08:57 2010
# Project:  Rationality.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile Rationality.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT_LIB -DQT_DBUS_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtSql -I/usr/include/QtDBus -I/usr/include/QtWebKit -I/usr/include -I. -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,--hash-style=gnu -Wl,--as-needed
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtWebKit -lQtDBus -lQtSql -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = QFreeDesktopMime/src/freedesktopmime.cpp \
		main.cpp \
		rationality.cpp \
		folderview.cpp \
		element.cpp \
		attribute.cpp \
		relation.cpp \
		relationbar.cpp \
		filedatabase.cpp \
		searchbutton.cpp \
		tagview.cpp \
		filterbar.cpp \
		leftbar.cpp \
		panelbutton.cpp \
		searchbar.cpp \
		backbutton.cpp \
		forwardbutton.cpp \
		filterbutton.cpp \
		propertybar.cpp \
		elementfile.cpp moc_freedesktopmime.cpp \
		moc_rationality.cpp \
		moc_folderview.cpp \
		moc_element.cpp \
		moc_attribute.cpp \
		moc_relation.cpp \
		moc_relationbar.cpp \
		moc_filedatabase.cpp \
		moc_searchbutton.cpp \
		moc_tagview.cpp \
		moc_filterbar.cpp \
		moc_leftbar.cpp \
		moc_panelbutton.cpp \
		moc_searchbar.cpp \
		moc_backbutton.cpp \
		moc_forwardbutton.cpp \
		moc_filterbutton.cpp \
		moc_propertybar.cpp \
		qrc_freedesktopmime.cpp \
		qrc_Resource.cpp
OBJECTS       = freedesktopmime.o \
		main.o \
		rationality.o \
		folderview.o \
		element.o \
		attribute.o \
		relation.o \
		relationbar.o \
		filedatabase.o \
		searchbutton.o \
		tagview.o \
		filterbar.o \
		leftbar.o \
		panelbutton.o \
		searchbar.o \
		backbutton.o \
		forwardbutton.o \
		filterbutton.o \
		propertybar.o \
		elementfile.o \
		moc_freedesktopmime.o \
		moc_rationality.o \
		moc_folderview.o \
		moc_element.o \
		moc_attribute.o \
		moc_relation.o \
		moc_relationbar.o \
		moc_filedatabase.o \
		moc_searchbutton.o \
		moc_tagview.o \
		moc_filterbar.o \
		moc_leftbar.o \
		moc_panelbutton.o \
		moc_searchbar.o \
		moc_backbutton.o \
		moc_forwardbutton.o \
		moc_filterbutton.o \
		moc_propertybar.o \
		qrc_freedesktopmime.o \
		qrc_Resource.o
DIST          = /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		QFreeDesktopMime/QFreeDesktopMime.pro \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		Rationality.pro
QMAKE_TARGET  = Rationality
DESTDIR       = 
TARGET        = Rationality

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_rationality.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Rationality.pro  /usr/share/qt/mkspecs/linux-g++-64/qmake.conf /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		QFreeDesktopMime/QFreeDesktopMime.pro \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtWebKit.prl \
		/usr/lib/libQtDBus.prl \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile Rationality.pro
/usr/share/qt/mkspecs/common/g++.conf:
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
QFreeDesktopMime/QFreeDesktopMime.pro:
/usr/share/qt/mkspecs/features/debug.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/dbusinterfaces.prf:
/usr/share/qt/mkspecs/features/dbusadaptors.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtWebKit.prl:
/usr/lib/libQtDBus.prl:
/usr/lib/libQtSql.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile Rationality.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Rationality1.0.0 || $(MKDIR) .tmp/Rationality1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Rationality1.0.0/ && $(COPY_FILE) --parents QFreeDesktopMime/src/freedesktopmime.h rationality.h folderview.h element.h attribute.h relation.h relationbar.h filedatabase.h searchbutton.h tagview.h filterbar.h leftbar.h panelbutton.h searchbar.h backbutton.h forwardbutton.h filter.h filterbutton.h propertybar.h elementfile.h .tmp/Rationality1.0.0/ && $(COPY_FILE) --parents QFreeDesktopMime/freedesktopmime.qrc Resource.qrc .tmp/Rationality1.0.0/ && $(COPY_FILE) --parents QFreeDesktopMime/src/freedesktopmime.cpp main.cpp rationality.cpp folderview.cpp element.cpp attribute.cpp relation.cpp relationbar.cpp filedatabase.cpp searchbutton.cpp tagview.cpp filterbar.cpp leftbar.cpp panelbutton.cpp searchbar.cpp backbutton.cpp forwardbutton.cpp filterbutton.cpp propertybar.cpp elementfile.cpp .tmp/Rationality1.0.0/ && $(COPY_FILE) --parents rationality.ui .tmp/Rationality1.0.0/ && (cd `dirname .tmp/Rationality1.0.0` && $(TAR) Rationality1.0.0.tar Rationality1.0.0 && $(COMPRESS) Rationality1.0.0.tar) && $(MOVE) `dirname .tmp/Rationality1.0.0`/Rationality1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Rationality1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_freedesktopmime.cpp moc_rationality.cpp moc_folderview.cpp moc_element.cpp moc_attribute.cpp moc_relation.cpp moc_relationbar.cpp moc_filedatabase.cpp moc_searchbutton.cpp moc_tagview.cpp moc_filterbar.cpp moc_leftbar.cpp moc_panelbutton.cpp moc_searchbar.cpp moc_backbutton.cpp moc_forwardbutton.cpp moc_filterbutton.cpp moc_propertybar.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_freedesktopmime.cpp moc_rationality.cpp moc_folderview.cpp moc_element.cpp moc_attribute.cpp moc_relation.cpp moc_relationbar.cpp moc_filedatabase.cpp moc_searchbutton.cpp moc_tagview.cpp moc_filterbar.cpp moc_leftbar.cpp moc_panelbutton.cpp moc_searchbar.cpp moc_backbutton.cpp moc_forwardbutton.cpp moc_filterbutton.cpp moc_propertybar.cpp
moc_freedesktopmime.cpp: QFreeDesktopMime/src/freedesktopmime.h
	/usr/bin/moc $(DEFINES) $(INCPATH) QFreeDesktopMime/src/freedesktopmime.h -o moc_freedesktopmime.cpp

moc_rationality.cpp: folderview.h \
		relation.h \
		element.h \
		tagview.h \
		filedatabase.h \
		filter.h \
		QFreeDesktopMime/src/freedesktopmime.h \
		leftbar.h \
		filterbar.h \
		searchbar.h \
		rationality.h
	/usr/bin/moc $(DEFINES) $(INCPATH) rationality.h -o moc_rationality.cpp

moc_folderview.cpp: relation.h \
		element.h \
		tagview.h \
		filedatabase.h \
		filter.h \
		QFreeDesktopMime/src/freedesktopmime.h \
		folderview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) folderview.h -o moc_folderview.cpp

moc_element.cpp: element.h
	/usr/bin/moc $(DEFINES) $(INCPATH) element.h -o moc_element.cpp

moc_attribute.cpp: attribute.h
	/usr/bin/moc $(DEFINES) $(INCPATH) attribute.h -o moc_attribute.cpp

moc_relation.cpp: element.h \
		tagview.h \
		relation.h
	/usr/bin/moc $(DEFINES) $(INCPATH) relation.h -o moc_relation.cpp

moc_relationbar.cpp: relationbar.h
	/usr/bin/moc $(DEFINES) $(INCPATH) relationbar.h -o moc_relationbar.cpp

moc_filedatabase.cpp: element.h \
		filter.h \
		QFreeDesktopMime/src/freedesktopmime.h \
		filedatabase.h
	/usr/bin/moc $(DEFINES) $(INCPATH) filedatabase.h -o moc_filedatabase.cpp

moc_searchbutton.cpp: searchbutton.h
	/usr/bin/moc $(DEFINES) $(INCPATH) searchbutton.h -o moc_searchbutton.cpp

moc_tagview.cpp: tagview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) tagview.h -o moc_tagview.cpp

moc_filterbar.cpp: filterbar.h
	/usr/bin/moc $(DEFINES) $(INCPATH) filterbar.h -o moc_filterbar.cpp

moc_leftbar.cpp: leftbar.h
	/usr/bin/moc $(DEFINES) $(INCPATH) leftbar.h -o moc_leftbar.cpp

moc_panelbutton.cpp: panelbutton.h
	/usr/bin/moc $(DEFINES) $(INCPATH) panelbutton.h -o moc_panelbutton.cpp

moc_searchbar.cpp: searchbar.h
	/usr/bin/moc $(DEFINES) $(INCPATH) searchbar.h -o moc_searchbar.cpp

moc_backbutton.cpp: backbutton.h
	/usr/bin/moc $(DEFINES) $(INCPATH) backbutton.h -o moc_backbutton.cpp

moc_forwardbutton.cpp: forwardbutton.h
	/usr/bin/moc $(DEFINES) $(INCPATH) forwardbutton.h -o moc_forwardbutton.cpp

moc_filterbutton.cpp: filterbutton.h
	/usr/bin/moc $(DEFINES) $(INCPATH) filterbutton.h -o moc_filterbutton.cpp

moc_propertybar.cpp: element.h \
		propertybar.h
	/usr/bin/moc $(DEFINES) $(INCPATH) propertybar.h -o moc_propertybar.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all: qrc_freedesktopmime.cpp qrc_Resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_freedesktopmime.cpp qrc_Resource.cpp
qrc_freedesktopmime.cpp: QFreeDesktopMime/freedesktopmime.qrc \
		QFreeDesktopMime/freedesktop.org.xml
	/usr/bin/rcc -name freedesktopmime QFreeDesktopMime/freedesktopmime.qrc -o qrc_freedesktopmime.cpp

qrc_Resource.cpp: Resource.qrc
	/usr/bin/rcc -name Resource Resource.qrc -o qrc_Resource.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_uic_make_all: ui_rationality.h
compiler_uic_clean:
	-$(DEL_FILE) ui_rationality.h
ui_rationality.h: rationality.ui
	/usr/bin/uic rationality.ui -o ui_rationality.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

freedesktopmime.o: QFreeDesktopMime/src/freedesktopmime.cpp QFreeDesktopMime/src/freedesktopmime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o freedesktopmime.o QFreeDesktopMime/src/freedesktopmime.cpp

main.o: main.cpp rationality.h \
		folderview.h \
		relation.h \
		element.h \
		tagview.h \
		filedatabase.h \
		filter.h \
		QFreeDesktopMime/src/freedesktopmime.h \
		leftbar.h \
		filterbar.h \
		searchbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

rationality.o: rationality.cpp rationality.h \
		folderview.h \
		relation.h \
		element.h \
		tagview.h \
		filedatabase.h \
		filter.h \
		QFreeDesktopMime/src/freedesktopmime.h \
		leftbar.h \
		filterbar.h \
		searchbar.h \
		ui_rationality.h \
		searchbutton.h \
		panelbutton.h \
		backbutton.h \
		forwardbutton.h \
		filterbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rationality.o rationality.cpp

folderview.o: folderview.cpp folderview.h \
		relation.h \
		element.h \
		tagview.h \
		filedatabase.h \
		filter.h \
		QFreeDesktopMime/src/freedesktopmime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o folderview.o folderview.cpp

element.o: element.cpp element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o element.o element.cpp

attribute.o: attribute.cpp attribute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o attribute.o attribute.cpp

relation.o: relation.cpp relation.h \
		element.h \
		tagview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o relation.o relation.cpp

relationbar.o: relationbar.cpp relationbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o relationbar.o relationbar.cpp

filedatabase.o: filedatabase.cpp filedatabase.h \
		element.h \
		filter.h \
		QFreeDesktopMime/src/freedesktopmime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filedatabase.o filedatabase.cpp

searchbutton.o: searchbutton.cpp searchbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o searchbutton.o searchbutton.cpp

tagview.o: tagview.cpp tagview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tagview.o tagview.cpp

filterbar.o: filterbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filterbar.o filterbar.cpp

leftbar.o: leftbar.cpp leftbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o leftbar.o leftbar.cpp

panelbutton.o: panelbutton.cpp panelbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o panelbutton.o panelbutton.cpp

searchbar.o: searchbar.cpp searchbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o searchbar.o searchbar.cpp

backbutton.o: backbutton.cpp backbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o backbutton.o backbutton.cpp

forwardbutton.o: forwardbutton.cpp forwardbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o forwardbutton.o forwardbutton.cpp

filterbutton.o: filterbutton.cpp filterbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filterbutton.o filterbutton.cpp

propertybar.o: propertybar.cpp propertybar.h \
		element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o propertybar.o propertybar.cpp

elementfile.o: elementfile.cpp elementfile.h \
		element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o elementfile.o elementfile.cpp

moc_freedesktopmime.o: moc_freedesktopmime.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_freedesktopmime.o moc_freedesktopmime.cpp

moc_rationality.o: moc_rationality.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rationality.o moc_rationality.cpp

moc_folderview.o: moc_folderview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_folderview.o moc_folderview.cpp

moc_element.o: moc_element.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_element.o moc_element.cpp

moc_attribute.o: moc_attribute.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_attribute.o moc_attribute.cpp

moc_relation.o: moc_relation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_relation.o moc_relation.cpp

moc_relationbar.o: moc_relationbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_relationbar.o moc_relationbar.cpp

moc_filedatabase.o: moc_filedatabase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filedatabase.o moc_filedatabase.cpp

moc_searchbutton.o: moc_searchbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_searchbutton.o moc_searchbutton.cpp

moc_tagview.o: moc_tagview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tagview.o moc_tagview.cpp

moc_filterbar.o: moc_filterbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filterbar.o moc_filterbar.cpp

moc_leftbar.o: moc_leftbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_leftbar.o moc_leftbar.cpp

moc_panelbutton.o: moc_panelbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_panelbutton.o moc_panelbutton.cpp

moc_searchbar.o: moc_searchbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_searchbar.o moc_searchbar.cpp

moc_backbutton.o: moc_backbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_backbutton.o moc_backbutton.cpp

moc_forwardbutton.o: moc_forwardbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_forwardbutton.o moc_forwardbutton.cpp

moc_filterbutton.o: moc_filterbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filterbutton.o moc_filterbutton.cpp

moc_propertybar.o: moc_propertybar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_propertybar.o moc_propertybar.cpp

qrc_freedesktopmime.o: qrc_freedesktopmime.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_freedesktopmime.o qrc_freedesktopmime.cpp

qrc_Resource.o: qrc_Resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Resource.o qrc_Resource.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

