#############################################################################
# Makefile for building: bin/Rationality
# Generated by qmake (2.01a) (Qt 4.6.2) on: dom lug 4 14:17:07 2010
# Project:  Rationality.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile Rationality.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_DBUS_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtSql -I/usr/include/QtDBus -I/usr/include/QtWebKit -I/usr/include -I. -Itmp -I.
LINK          = g++
LFLAGS        = -m64 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtWebKit -lQtDBus -lQtSql -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = QFreeDesktopMime/src/freedesktopmime.cpp \
		main.cpp \
		rationality.cpp \
		folderview.cpp \
		element.cpp \
		attribute.cpp \
		relation.cpp \
		relationbar.cpp \
		filedatabase.cpp \
		searchbutton.cpp \
		tagview.cpp \
		filterbar.cpp \
		leftbar.cpp \
		panelbutton.cpp \
		searchbar.cpp \
		backbutton.cpp \
		forwardbutton.cpp \
		filterbutton.cpp \
		propertybar.cpp \
		elementfile.cpp tmp/moc_freedesktopmime.cpp \
		tmp/moc_rationality.cpp \
		tmp/moc_folderview.cpp \
		tmp/moc_element.cpp \
		tmp/moc_attribute.cpp \
		tmp/moc_relation.cpp \
		tmp/moc_relationbar.cpp \
		tmp/moc_filedatabase.cpp \
		tmp/moc_searchbutton.cpp \
		tmp/moc_tagview.cpp \
		tmp/moc_filterbar.cpp \
		tmp/moc_leftbar.cpp \
		tmp/moc_panelbutton.cpp \
		tmp/moc_searchbar.cpp \
		tmp/moc_backbutton.cpp \
		tmp/moc_forwardbutton.cpp \
		tmp/moc_filterbutton.cpp \
		tmp/moc_propertybar.cpp \
		qrc_freedesktopmime.cpp \
		qrc_Resource.cpp
OBJECTS       = obj/freedesktopmime.o \
		obj/main.o \
		obj/rationality.o \
		obj/folderview.o \
		obj/element.o \
		obj/attribute.o \
		obj/relation.o \
		obj/relationbar.o \
		obj/filedatabase.o \
		obj/searchbutton.o \
		obj/tagview.o \
		obj/filterbar.o \
		obj/leftbar.o \
		obj/panelbutton.o \
		obj/searchbar.o \
		obj/backbutton.o \
		obj/forwardbutton.o \
		obj/filterbutton.o \
		obj/propertybar.o \
		obj/elementfile.o \
		obj/moc_freedesktopmime.o \
		obj/moc_rationality.o \
		obj/moc_folderview.o \
		obj/moc_element.o \
		obj/moc_attribute.o \
		obj/moc_relation.o \
		obj/moc_relationbar.o \
		obj/moc_filedatabase.o \
		obj/moc_searchbutton.o \
		obj/moc_tagview.o \
		obj/moc_filterbar.o \
		obj/moc_leftbar.o \
		obj/moc_panelbutton.o \
		obj/moc_searchbar.o \
		obj/moc_backbutton.o \
		obj/moc_forwardbutton.o \
		obj/moc_filterbutton.o \
		obj/moc_propertybar.o \
		obj/qrc_freedesktopmime.o \
		obj/qrc_Resource.o
DIST          = /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		QFreeDesktopMime/QFreeDesktopMime.pro \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		Rationality.pro
QMAKE_TARGET  = Rationality
DESTDIR       = bin/
TARGET        = bin/Rationality

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_rationality.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Rationality.pro  /usr/share/qt/mkspecs/linux-g++-64/qmake.conf /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		QFreeDesktopMime/QFreeDesktopMime.pro \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtWebKit.prl \
		/usr/lib/libQtDBus.prl \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile Rationality.pro
/usr/share/qt/mkspecs/common/g++.conf:
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
QFreeDesktopMime/QFreeDesktopMime.pro:
/usr/share/qt/mkspecs/features/release.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/dbusinterfaces.prf:
/usr/share/qt/mkspecs/features/dbusadaptors.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtWebKit.prl:
/usr/lib/libQtDBus.prl:
/usr/lib/libQtSql.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile Rationality.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/Rationality1.0.0 || $(MKDIR) obj/Rationality1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/Rationality1.0.0/ && $(COPY_FILE) --parents QFreeDesktopMime/src/freedesktopmime.h rationality.h folderview.h element.h attribute.h relation.h relationbar.h filedatabase.h searchbutton.h tagview.h filterbar.h leftbar.h panelbutton.h searchbar.h backbutton.h forwardbutton.h filter.h filterbutton.h propertybar.h elementfile.h obj/Rationality1.0.0/ && $(COPY_FILE) --parents QFreeDesktopMime/freedesktopmime.qrc Resource.qrc obj/Rationality1.0.0/ && $(COPY_FILE) --parents QFreeDesktopMime/src/freedesktopmime.cpp main.cpp rationality.cpp folderview.cpp element.cpp attribute.cpp relation.cpp relationbar.cpp filedatabase.cpp searchbutton.cpp tagview.cpp filterbar.cpp leftbar.cpp panelbutton.cpp searchbar.cpp backbutton.cpp forwardbutton.cpp filterbutton.cpp propertybar.cpp elementfile.cpp obj/Rationality1.0.0/ && $(COPY_FILE) --parents rationality.ui obj/Rationality1.0.0/ && (cd `dirname obj/Rationality1.0.0` && $(TAR) Rationality1.0.0.tar Rationality1.0.0 && $(COMPRESS) Rationality1.0.0.tar) && $(MOVE) `dirname obj/Rationality1.0.0`/Rationality1.0.0.tar.gz . && $(DEL_FILE) -r obj/Rationality1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: tmp/moc_freedesktopmime.cpp tmp/moc_rationality.cpp tmp/moc_folderview.cpp tmp/moc_element.cpp tmp/moc_attribute.cpp tmp/moc_relation.cpp tmp/moc_relationbar.cpp tmp/moc_filedatabase.cpp tmp/moc_searchbutton.cpp tmp/moc_tagview.cpp tmp/moc_filterbar.cpp tmp/moc_leftbar.cpp tmp/moc_panelbutton.cpp tmp/moc_searchbar.cpp tmp/moc_backbutton.cpp tmp/moc_forwardbutton.cpp tmp/moc_filterbutton.cpp tmp/moc_propertybar.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) tmp/moc_freedesktopmime.cpp tmp/moc_rationality.cpp tmp/moc_folderview.cpp tmp/moc_element.cpp tmp/moc_attribute.cpp tmp/moc_relation.cpp tmp/moc_relationbar.cpp tmp/moc_filedatabase.cpp tmp/moc_searchbutton.cpp tmp/moc_tagview.cpp tmp/moc_filterbar.cpp tmp/moc_leftbar.cpp tmp/moc_panelbutton.cpp tmp/moc_searchbar.cpp tmp/moc_backbutton.cpp tmp/moc_forwardbutton.cpp tmp/moc_filterbutton.cpp tmp/moc_propertybar.cpp
tmp/moc_freedesktopmime.cpp: QFreeDesktopMime/src/freedesktopmime.h
	/usr/bin/moc $(DEFINES) $(INCPATH) QFreeDesktopMime/src/freedesktopmime.h -o tmp/moc_freedesktopmime.cpp

tmp/moc_rationality.cpp: folderview.h \
		relation.h \
		element.h \
		tagview.h \
		filedatabase.h \
		elementfile.h \
		filter.h \
		QFreeDesktopMime/src/freedesktopmime.h \
		leftbar.h \
		filterbar.h \
		searchbar.h \
		rationality.h
	/usr/bin/moc $(DEFINES) $(INCPATH) rationality.h -o tmp/moc_rationality.cpp

tmp/moc_folderview.cpp: relation.h \
		element.h \
		tagview.h \
		filedatabase.h \
		elementfile.h \
		filter.h \
		QFreeDesktopMime/src/freedesktopmime.h \
		folderview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) folderview.h -o tmp/moc_folderview.cpp

tmp/moc_element.cpp: element.h
	/usr/bin/moc $(DEFINES) $(INCPATH) element.h -o tmp/moc_element.cpp

tmp/moc_attribute.cpp: attribute.h
	/usr/bin/moc $(DEFINES) $(INCPATH) attribute.h -o tmp/moc_attribute.cpp

tmp/moc_relation.cpp: element.h \
		tagview.h \
		relation.h
	/usr/bin/moc $(DEFINES) $(INCPATH) relation.h -o tmp/moc_relation.cpp

tmp/moc_relationbar.cpp: relationbar.h
	/usr/bin/moc $(DEFINES) $(INCPATH) relationbar.h -o tmp/moc_relationbar.cpp

tmp/moc_filedatabase.cpp: elementfile.h \
		element.h \
		filter.h \
		QFreeDesktopMime/src/freedesktopmime.h \
		filedatabase.h
	/usr/bin/moc $(DEFINES) $(INCPATH) filedatabase.h -o tmp/moc_filedatabase.cpp

tmp/moc_searchbutton.cpp: searchbutton.h
	/usr/bin/moc $(DEFINES) $(INCPATH) searchbutton.h -o tmp/moc_searchbutton.cpp

tmp/moc_tagview.cpp: tagview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) tagview.h -o tmp/moc_tagview.cpp

tmp/moc_filterbar.cpp: filterbar.h
	/usr/bin/moc $(DEFINES) $(INCPATH) filterbar.h -o tmp/moc_filterbar.cpp

tmp/moc_leftbar.cpp: leftbar.h
	/usr/bin/moc $(DEFINES) $(INCPATH) leftbar.h -o tmp/moc_leftbar.cpp

tmp/moc_panelbutton.cpp: panelbutton.h
	/usr/bin/moc $(DEFINES) $(INCPATH) panelbutton.h -o tmp/moc_panelbutton.cpp

tmp/moc_searchbar.cpp: searchbar.h
	/usr/bin/moc $(DEFINES) $(INCPATH) searchbar.h -o tmp/moc_searchbar.cpp

tmp/moc_backbutton.cpp: backbutton.h
	/usr/bin/moc $(DEFINES) $(INCPATH) backbutton.h -o tmp/moc_backbutton.cpp

tmp/moc_forwardbutton.cpp: forwardbutton.h
	/usr/bin/moc $(DEFINES) $(INCPATH) forwardbutton.h -o tmp/moc_forwardbutton.cpp

tmp/moc_filterbutton.cpp: filterbutton.h
	/usr/bin/moc $(DEFINES) $(INCPATH) filterbutton.h -o tmp/moc_filterbutton.cpp

tmp/moc_propertybar.cpp: element.h \
		propertybar.h
	/usr/bin/moc $(DEFINES) $(INCPATH) propertybar.h -o tmp/moc_propertybar.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all: qrc_freedesktopmime.cpp qrc_Resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_freedesktopmime.cpp qrc_Resource.cpp
qrc_freedesktopmime.cpp: QFreeDesktopMime/freedesktopmime.qrc \
		QFreeDesktopMime/freedesktop.org.xml
	/usr/bin/rcc -name freedesktopmime QFreeDesktopMime/freedesktopmime.qrc -o qrc_freedesktopmime.cpp

qrc_Resource.cpp: Resource.qrc
	/usr/bin/rcc -name Resource Resource.qrc -o qrc_Resource.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_uic_make_all: ui_rationality.h
compiler_uic_clean:
	-$(DEL_FILE) ui_rationality.h
ui_rationality.h: rationality.ui
	/usr/bin/uic rationality.ui -o ui_rationality.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

obj/freedesktopmime.o: QFreeDesktopMime/src/freedesktopmime.cpp QFreeDesktopMime/src/freedesktopmime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/freedesktopmime.o QFreeDesktopMime/src/freedesktopmime.cpp

obj/main.o: main.cpp rationality.h \
		folderview.h \
		relation.h \
		element.h \
		tagview.h \
		filedatabase.h \
		elementfile.h \
		filter.h \
		QFreeDesktopMime/src/freedesktopmime.h \
		leftbar.h \
		filterbar.h \
		searchbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/rationality.o: rationality.cpp rationality.h \
		folderview.h \
		relation.h \
		element.h \
		tagview.h \
		filedatabase.h \
		elementfile.h \
		filter.h \
		QFreeDesktopMime/src/freedesktopmime.h \
		leftbar.h \
		filterbar.h \
		searchbar.h \
		ui_rationality.h \
		searchbutton.h \
		panelbutton.h \
		backbutton.h \
		forwardbutton.h \
		filterbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/rationality.o rationality.cpp

obj/folderview.o: folderview.cpp folderview.h \
		relation.h \
		element.h \
		tagview.h \
		filedatabase.h \
		elementfile.h \
		filter.h \
		QFreeDesktopMime/src/freedesktopmime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/folderview.o folderview.cpp

obj/element.o: element.cpp element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/element.o element.cpp

obj/attribute.o: attribute.cpp attribute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/attribute.o attribute.cpp

obj/relation.o: relation.cpp relation.h \
		element.h \
		tagview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/relation.o relation.cpp

obj/relationbar.o: relationbar.cpp relationbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/relationbar.o relationbar.cpp

obj/filedatabase.o: filedatabase.cpp filedatabase.h \
		elementfile.h \
		element.h \
		filter.h \
		QFreeDesktopMime/src/freedesktopmime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/filedatabase.o filedatabase.cpp

obj/searchbutton.o: searchbutton.cpp searchbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/searchbutton.o searchbutton.cpp

obj/tagview.o: tagview.cpp tagview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/tagview.o tagview.cpp

obj/filterbar.o: filterbar.cpp filterbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/filterbar.o filterbar.cpp

obj/leftbar.o: leftbar.cpp leftbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/leftbar.o leftbar.cpp

obj/panelbutton.o: panelbutton.cpp panelbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/panelbutton.o panelbutton.cpp

obj/searchbar.o: searchbar.cpp searchbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/searchbar.o searchbar.cpp

obj/backbutton.o: backbutton.cpp backbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/backbutton.o backbutton.cpp

obj/forwardbutton.o: forwardbutton.cpp forwardbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/forwardbutton.o forwardbutton.cpp

obj/filterbutton.o: filterbutton.cpp filterbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/filterbutton.o filterbutton.cpp

obj/propertybar.o: propertybar.cpp propertybar.h \
		element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/propertybar.o propertybar.cpp

obj/elementfile.o: elementfile.cpp elementfile.h \
		element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/elementfile.o elementfile.cpp

obj/moc_freedesktopmime.o: tmp/moc_freedesktopmime.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_freedesktopmime.o tmp/moc_freedesktopmime.cpp

obj/moc_rationality.o: tmp/moc_rationality.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_rationality.o tmp/moc_rationality.cpp

obj/moc_folderview.o: tmp/moc_folderview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_folderview.o tmp/moc_folderview.cpp

obj/moc_element.o: tmp/moc_element.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_element.o tmp/moc_element.cpp

obj/moc_attribute.o: tmp/moc_attribute.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_attribute.o tmp/moc_attribute.cpp

obj/moc_relation.o: tmp/moc_relation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_relation.o tmp/moc_relation.cpp

obj/moc_relationbar.o: tmp/moc_relationbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_relationbar.o tmp/moc_relationbar.cpp

obj/moc_filedatabase.o: tmp/moc_filedatabase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_filedatabase.o tmp/moc_filedatabase.cpp

obj/moc_searchbutton.o: tmp/moc_searchbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_searchbutton.o tmp/moc_searchbutton.cpp

obj/moc_tagview.o: tmp/moc_tagview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_tagview.o tmp/moc_tagview.cpp

obj/moc_filterbar.o: tmp/moc_filterbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_filterbar.o tmp/moc_filterbar.cpp

obj/moc_leftbar.o: tmp/moc_leftbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_leftbar.o tmp/moc_leftbar.cpp

obj/moc_panelbutton.o: tmp/moc_panelbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_panelbutton.o tmp/moc_panelbutton.cpp

obj/moc_searchbar.o: tmp/moc_searchbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_searchbar.o tmp/moc_searchbar.cpp

obj/moc_backbutton.o: tmp/moc_backbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_backbutton.o tmp/moc_backbutton.cpp

obj/moc_forwardbutton.o: tmp/moc_forwardbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_forwardbutton.o tmp/moc_forwardbutton.cpp

obj/moc_filterbutton.o: tmp/moc_filterbutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_filterbutton.o tmp/moc_filterbutton.cpp

obj/moc_propertybar.o: tmp/moc_propertybar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_propertybar.o tmp/moc_propertybar.cpp

obj/qrc_freedesktopmime.o: qrc_freedesktopmime.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_freedesktopmime.o qrc_freedesktopmime.cpp

obj/qrc_Resource.o: qrc_Resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_Resource.o qrc_Resource.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

