######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 2 16:36:07 2008
######################################################################

DEPENDPATH += .
INCLUDEPATH += .

QT += xml

# Input
HEADERS += QFreeDesktopMime/src/freedesktopmime.h
SOURCES += QFreeDesktopMime/src/freedesktopmime.cpp
RESOURCES += QFreeDesktopMime/freedesktopmime.qrc
